{
 "title": "Flight Controller dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Guardrail Max Activations Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "\"core_timestream_db\"",
     "measure": "guardrail_max_activation",
     "rawQuery": "SELECT bin(time, $__interval) as binned_time, AVG(\"measure_value\"::double)\nFROM $__database.$__table\nWHERE \"measure_name\" = '$__measure' AND $__timeFilter\nGROUP BY bin(time, $__interval)\nORDER BY binned_time",
     "table": "\"metrics_table\""
    }
   ]
  },
  {
   "title": "Guardrail Total Activation Count",
   "type": "bargauge",
   "description": "Guardrail Total Activation Count per Resource and Guardrail ID.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "\"core_timestream_db\"",
     "measure": "guardrail_activation_count",
     "rawQuery": "SELECT \"aggregate_id\", \"guardrail_id\", MAX(\"measure_value\"::double) as \"total_activations\" FROM $__database.$__table\nWHERE \"measure_name\" = '$__measure' AND $__timeFilter\nGROUP BY \"aggregate_id\", \"guardrail_id\"\nORDER BY \"total_activations\" DESC",
     "table": "\"metrics_table\""
    }
   ]
  },
  {
   "title": "Guardrail Lead Time Average",
   "type": "bargauge",
   "description": "Average lead time from last pertinent activation to resolution.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"core_timestream_db\"",
     "measure": "guardrail_lead_time",
     "rawQuery": "SELECT \"aggregate_id\", \"guardrail_id\", AVG(\"measure_value\"::double) as \"average_lead_time\" FROM $__database.$__table\nWHERE \"measure_name\" = '$__measure' AND $__timeFilter\nGROUP BY \"aggregate_id\", \"guardrail_id\"\nORDER BY \"average_lead_time\" DESC",
     "table": "\"metrics_table\""
    }
   ]
  },
  {
   "title": "Patch Compliance %",
   "type": "gauge",
   "description": "Percentage based on the number of patch compliant instances.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"core_timestream_db\"",
     "measure": "patch_compliance_percentage",
     "rawQuery": "SELECT \"measure_value\"::double FROM $__database.$__table\nWHERE \"measure_name\" = '$__measure' AND $__timeFilter\nORDER BY \"time\" ASC",
     "table": "\"metrics_table\""
    }
   ]
  },
  {
   "title": "Resource Compliance Lead Time (Average)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "\"core_timestream_db\"",
     "measure": "resource_compliance_lead_time",
     "rawQuery": "SELECT \"measure_value\"::double FROM $__database.$__table\nWHERE \"measure_name\" = '$__measure' AND $__timeFilter\nORDER BY \"time\" ASC",
     "table": "\"metrics_table\""
    }
   ]
  },
  {
   "title": "Project Lead Time (Average)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "\"core_timestream_db\"",
     "measure": "project_lead_time",
     "rawQuery": "SELECT \"measure_value\"::double FROM $__database.$__table\nWHERE \"measure_name\" = '$__measure' AND $__timeFilter\nORDER BY \"time\" ASC",
     "table": "\"metrics_table\""
    }
   ]
  },
  {
   "title": "Account Lead Time (Average)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "\"core_timestream_db\"",
     "measure": "account_lead_time",
     "rawQuery": "SELECT \"measure_value\"::double FROM $__database.$__table\nWHERE \"measure_name\" = '$__measure' AND $__timeFilter\nORDER BY \"time\" ASC",
     "table": "\"metrics_table\""
    }
   ]
  },
  {
   "title": "Identity Lead Time (Average)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "\"core_timestream_db\"",
     "measure": "identity_lead_time",
     "rawQuery": "SELECT \"measure_value\"::double FROM $__database.$__table\nWHERE \"measure_name\" = '$__measure' AND $__timeFilter\nORDER BY \"time\" ASC",
     "table": "\"metrics_table\""
    }
   ]
  }
 ]
}